fix hero, divide bg-images
ssevik/team-project-iceCream pull request #26
Opened 2022-01-18 09:35 UTC by dnkolga

Починен h1, разделены фоновые изображения по разным оберткам для стилизации

2022-01-18 12:41 UTC, ssevik requested changes
строка 6 в header.scss padding-top: 6px; не вложен. И надо sass с делать влажность не такую большую очень тяжело читать

2022-01-18 12:41 UTC, ssevik commented on src/sass/_header.scss
> +        &--lady {
Бекграун с кругом перекрывает картинку с девушкой

2022-01-19 08:06 UTC, dnkolga commented
> строка 6 в header.scss padding-top: 6px; не вложен. И надо sass с делать влажность не такую большую очень тяжело читать

куда не вложен padding-top: 6px ?

2022-01-19 13:35 UTC, ssevik approved these changes

2022-01-19 13:40 UTC, merged