Feature/mobile menu
ssevik/team-project-iceCream pull request #5
Opened 2022-01-14 19:54 UTC by Olena-Milham

2022-01-15 16:03 UTC, d3nnys requested changes

2022-01-15 16:03 UTC, d3nnys commented on src/sass/_mobile-menu.scss
> +  }
@media screen and (min-width: 1200px) {
    display: none;
  }

2022-01-15 16:03 UTC, d3nnys commented on src/sass/_mobile-menu.scss
> +  margin-bottom: 23px;
убрать

2022-01-15 16:03 UTC, d3nnys commented on src/sass/_mobile-menu.scss
> +    padding-top: 33px;
убрать

2022-01-15 16:03 UTC, d3nnys commented on src/sass/_mobile-menu.scss
> +  padding-top: 10px;
изменить на padding-top: 11px;

2022-01-15 16:03 UTC, d3nnys commented on src/sass/_mobile-menu.scss
> +  margin: 0 auto;
убрать

2022-01-15 16:03 UTC, d3nnys commented on src/sass/_mobile-menu.scss
> +    width: 186px;
добавить margin-left: 10px;

2022-01-15 16:10 UTC, ssevik requested changes

2022-01-15 16:10 UTC, ssevik commented on src/sass/_mobile-menu.scss
> +  }
re

2022-01-15 17:03 UTC, Olena-Milham commented on src/sass/_mobile-menu.scss
> +  }
done

2022-01-15 17:03 UTC, Olena-Milham commented on src/sass/_mobile-menu.scss
> +  margin-bottom: 23px;
done

2022-01-15 17:04 UTC, Olena-Milham commented on src/sass/_mobile-menu.scss
> +    padding-top: 33px;
done

2022-01-15 17:05 UTC, Olena-Milham commented on src/sass/_mobile-menu.scss
> +  padding-top: 10px;
done

2022-01-15 17:06 UTC, Olena-Milham commented on src/sass/_mobile-menu.scss
> +  margin: 0 auto;
margin: 0 auto - kill - done

2022-01-15 17:07 UTC, Olena-Milham commented on src/sass/_mobile-menu.scss
> +    width: 186px;
done

2022-01-16 10:36 UTC, d3nnys requested changes
перенеси в файле src/sass/_mobile-menu.scss 73 строку на 75, марджин-лефт в медиазапрос с 768px

2022-01-16 14:37 UTC, d3nnys approved these changes

2022-01-16 14:46 UTC, ssevik approved these changes

2022-01-16 14:46 UTC, merged