feature/products
ssevik/team-project-iceCream pull request #6
Opened 2022-01-15 13:22 UTC by ssevik

2022-01-15 14:45 UTC, ssevik commented on src/index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com" />
а зачем подключать шрифт?

2022-01-15 14:45 UTC, ssevik commented on src/sass/_general.scss
> +    width: 1200px;
width: 1200px; не нужен тут макс должен быть я уже исправил

2022-01-15 14:45 UTC, ssevik commented on src/sass/_products.scss
> +  font-style: normal;
не нужен

2022-01-15 14:45 UTC, ssevik commented on src/sass/_products.scss
> +  text-align: center;
не нужен

2022-01-15 14:45 UTC, ssevik commented on src/sass/_products.scss
> +  letter-spacing: 0.04em;
не нужен

2022-01-15 14:45 UTC, ssevik commented on src/sass/_products.scss
> +  justify-content: center;
не нужен

2022-01-15 14:45 UTC, ssevik commented on src/sass/_products.scss
> +  font-style: normal;
не нужен

2022-01-15 14:45 UTC, ssevik commented on src/sass/_products.scss
> +  background: url(../images/products/arrow-right.jpg) no-repeat center center;
тут png так как меньше весит

2022-01-15 14:45 UTC, ssevik commented on src/sass/_products.scss
> +    background: url(../images/products/320px/product-1-320-2x.png);
тут картинки которые в 2x обрезаются надо бекграунд сайт ковер и там у все проблема на 2x

2022-01-15 15:00 UTC, d3nnys requested changes

2022-01-15 15:00 UTC, d3nnys commented on src/sass/_products.scss
> +    padding-bottom: 112px;
padding-bottom: 119px;

2022-01-16 11:45 UTC, d3nnys approved these changes

2022-01-16 11:48 UTC, merged